# Generated by Django 4.2.5 on 2023-10-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="newspaper",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="newspapers",
                to="agency.topic",
            ),
        ),
    ]
